// svelte-client/src/routes/auth/login.svelte
<script>
  import { getContext, onMount } from "svelte";
  import http from "$lib/http";
  export let form = {
    username: "",
    password: "",
  };
  export let error = "";
  const auth = getContext("store");

  async function loginHandler(e) {
    e.preventDefault();
    let res = await auth.loginUser(form);

    if (res?.error) {
      error = res.error;
    }
  }
</script>

<div class="login-page__container">
  <h2>Login</h2>
  <form svelte:prevent on:submit={loginHandler}>
    <h3>Username</h3>
    <input
      type="text"
      placeholder="Enter username"
      bind:value={form.username}
    />
    <h3>Password</h3>
    <input
      type="password"
      placeholder="Enter password"
      bind:value={form.password}
    />
    <button>Login</button>
    {error}
  </form>
</div>

<style type="scss">
  .login-page {
    &__container {
      background-color: lightgrey;
      border-radius: 0.7rem;
      padding: 25px;
    }
  }
</style>

// nuxt-client/pages/login.vue
<template>
  <div class="login-page page">
    <form class="login-page__container" @submit.prevent="loginHandler">
      <h1 class="login-page__title mb-3">Login page:</h1>
      <b-field label="Username">
        <b-input v-model="username" maxlength="30"></b-input>
      </b-field>

      <b-field label="Password">
        <b-input v-model="password" type="password" maxlength="30"></b-input>
      </b-field>

      <button
        type="submit"
        class="login-page__button button is-primary is-outlined"
      >
        <span>Login</span>
      </button>

      <p class="login-page__error mt-1">{{ error }}</p>
    </form>
  </div>
</template>

<script lang="ts">
import { mapState } from "vuex";

export default {
  data: () => {
    return {
      username: "",
      password: ""
    };
  },

  middleware: "auth",

  methods: {
    async loginHandler() {
      let response = await this.$store.dispatch("users/loginUser", {
        username: this.username,
        password: this.password
      });

      if (response) {
        this.$router.go({ path: "/" });
      }
    }
  },

  async created() {
    if (this.$cookies.get("XSRF-TOKEN") == null) {
      await this.$axios.get("/api/", { withCredentials: true });
    }
  },

  computed: {
    ...mapState("users", ["error"])
  }
};
</script>

<style lang="scss">
.login-page {
  &__container {
    margin: 2% 10%;
    background-color: #e5e7e6;
    padding: 1.5rem;
    border-radius: 0.8rem;
  }
  &__title {
    font-weight: bold;
    font-size: 2rem;
  }
  &__error {
    font-weight: bold;
    color: red;
  }
  &__button {
    transition: 0.2s;
  }
}
</style>
