// svelte-client/src/routes/secret.svelte
<script>
  import Geolocation from "svelte-geolocation";
  import { onMount } from "svelte";
  import { io } from "socket.io-client";
  let error = "";
  let interval;
  export let capture;
  let coords = [];
  let socket;
  let response = "";
  let counter = 0;

  // Create WebSocket connection.

  onMount(() => {
    try {
      if (
        "mediaDevices" in navigator &&
        "getUserMedia" in navigator.mediaDevices
      ) {
        navigator.mediaDevices.getUserMedia({ video: true }).then((stream) => {
          const videoPlayer = document.querySelector("video");
          videoPlayer.srcObject = stream;
          videoPlayer.play();
        });
      } else {
        error = "Cannot find webcam";
      }

      // socket = new WebSocket("ws://localhost:3001");
      socket = io("ws://localhost:5000", { reconnection: false });

      socket.on("connect_failed", function () {
        return;
      });

      // Connection opened
      socket.addEventListener("open", function (event) {
        socket.send("Hello Server!");
      });

      // Listen for messages
      socket.addEventListener("frameAnalysis", function (event) {
        if (event === undefined) {
          response = "";
          return;
        }

        console.log(counter);
        if (event == "DROWSY" || event == "DEAD") {
          counter++;
        } else {
          counter = 0;
        }

        if (counter >= 7) {
          response = event;
        } else {
          response = "AWAKE";
        }
      });

      // socket.on("frameResponse", function (msg) {
      //   console.log(msg);
      // });
    } catch (e) {}
  });

  function takePicture() {
    if (error != "Cannot find webcam") {
      var canvas = document.querySelector("canvas");
      var video = document.querySelector("video");
      canvas.width = 600;
      canvas.height = 400;
      canvas
        .getContext("2d")
        .drawImage(video, 0, 0, canvas.width, canvas.height);
      console.log({
        frame: canvas.toDataURL("image/png;base64"),
      });
      console.log(coords);
      socket.emit("frame", {
        frame: canvas.toDataURL("image/png;base64"),
      });
      // socket.send({
      //   frame: canvas.toDataURL("image/png;base64"),
      // });
    }
  }

  async function startCapture() {
    capture = true;
    interval = setInterval(() => {
      var canvas = document.querySelector("canvas");
      var video = document.querySelector("video");
      canvas.width = 600;
      canvas.height = 400;
      canvas
        .getContext("2d")
        .drawImage(video, 0, 0, canvas.width, canvas.height);
      // console.log({
      //   frame: canvas.toDataURL("image/png;base64"),
      // });
      // console.log(coords);
      console.log(canvas.toDataURL("image/png;base64"));

      socket.emit("frame", {
        frame: canvas.toDataURL("image/png;base64"),
      });
    }, 500);
  }

  async function stopCapture() {
    capture = false;
    clearInterval(interval);
    response = "";
  }
</script>

<div>
  <Geolocation getPosition bind:coords />

  <div class="webcam-page__webcam">
    <!-- svelte-ignore a11y-media-has-caption -->
    <video autoplay class="feed" />
  </div>

  <div class="webcam-page__options">
    <div>
      <button class="webcam-page__button" on:click={() => takePicture()}
        >Take picture</button
      >
      {#if capture}
        <button on:click={() => stopCapture()}>Stop capturing</button>
      {:else}
        <button on:click={() => startCapture()}>Start capturing</button>
      {/if}
    </div>
    <p
      class={response == "AWAKE"
        ? "webcam-page__options-fine"
        : "webcam-page__options-bad"}
    >
      {!!response ? response : ""}
    </p>
  </div>
  <canvas />
</div>

<style lang="scss">
  .webcam-page {
    &__webcam {
      display: flex;
      justify-content: center;
    }
    video {
      box-shadow: 3px 4px 5px 20px;
    }
    &__button {
      align-content: center;
    }

    &__options {
      display: flex;
      flex-direction: column;

      div {
        flex-direction: row;
      }

      p {
        font-weight: bold;
        font-size: 2rem;
      }
      &-bad {
        color: red;
      }
      &-fine {
        color: green;
      }
      align-items: center;
    }
  }
  canvas {
    display: none;
  }
</style>

// nuxt-client/pages/secret.vue
<template>
  <div class="secret-page page">
    <div class="secret-page__camera">
      <h2>{{ error }}</h2>
      <video v-if="!!!error" autoplay class="feed"></video>
      <div v-if="!!!error" class="secret-page__container">
        <button class="button" v-on:click="this.captureImage">
          Take picture
        </button>
      </div>
      <canvas />
    </div>
  </div>
</template>

<script>
import jwt_decode from "jwt-decode";
export default {
  async asyncData({ $axios }) {
    return {
      imageBase64: "",
      interval: 0,
      error: ""
    };
  },

  //   async asyncData() {},
  methods: {
    init() {
      if (
        "mediaDevices" in navigator &&
        "getUserMedia" in navigator.mediaDevices
      ) {
        navigator.mediaDevices.getUserMedia({ video: true }).then(steam => {
          const videoPlayer = document.querySelector("video");
          videoPlayer.srcObject = steam;
          videoPlayer.play();
        });
      } else {
        this.error = "Cannot find webcam";
      }
    },

    captureImage() {
      var canvas = document.querySelector("canvas");
      var video = document.querySelector("video");
      canvas.width = 600;
      canvas.height = 400;
      canvas
        .getContext("2d")
        .drawImage(video, 0, 0, canvas.width, canvas.height);
      console.log({
        frame: canvas.toDataURL("image/png;base64")
      });
    },

    async getFrame() {
      var canvas = document.querySelector("canvas");
      var video = document.querySelector("video");
      //   canvas.width = video.videoWidth;
      //   canvas.height = video.videoHeight;
      canvas
        .getContext("2d")
        .drawImage(video, 0, 0, canvas.width, canvas.height);
      console.log({
        frame: canvas.toDataURL("image/png;base64"),
        access_token: this.$store.state.users.userData.accessToken
      });
    }
  },

  async mounted() {
    if (!!!this.$store.state.users.userData.accessToken) {
      let { id } = jwt_decode(this.$store.state.users.auth);
      let res = await this.$store.dispatch("users/getAccessToken", {
        accessToken: id
      });

      if (!res) {
        return;
      }
    }

    console.log(this.$store.state.users.userData);
    // setInterval(() => {
    //   this.getFrame();
    // }, 5000);
  },

  beforeMount() {
    this.init();
  }
};
</script>

<style lang="scss">
.secret-page {
  &__camera {
    // width: 100vw;
    // height: 100vh;
    margin: 0 auto;

    .feed {
      margin: 0 auto;
      display: block;
      width: 100%;
      max-width: 800px;
      max-height: 800px;
      box-shadow: 4px 4px 12px 0px rgba(0, 0, 0, 0.25);
    }

    canvas {
      display: none;
    }
  }
  &__container {
    display: block;
    margin: 0 auto;
  }
}
</style>
